# .github/workflows/ci.yml

name: Deploy MaRe Documentation

# Controls when the action will run. 
# Triggers the workflow on push events but only for the main branch.
on:
  push:
    branches:
      - master 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install MkDocs and the Material theme
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      # Step 4: Build and deploy the site to the gh-pages branch
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean

